blank_issues_enabled: false
contact_links:
  - name: ğŸ“„ å®˜æ–¹æ–‡æ¡£
    url: https://layui.dev/
    about: å»ºè®®åœ¨åˆ›å»º Issue ä¹‹å‰ï¼Œä»”ç»†æŸ¥é˜… Layui å¼€å‘æ–‡æ¡£ï¼Œä»¥ä¾¿å¯¹å…¶æœ‰æ›´æ·±å…¥çš„äº†è§£ï¼Œå’Œæ›´å¥½åœ°åˆ†æé—®é¢˜ã€‚
  - name: ğŸ” Gitee Issues
    url: https://gitee.com/layui/layui/issues
    about: ä»è¿‡å¾€çš„ 6000+ Issues ä¸­æœç´¢ç›¸ä¼¼è®®é¢˜ï¼Œä¸»è¦é€‚ç”¨äº 2.x ç‰ˆæœ¬
