blank_issues_enabled: false
contact_links:
  - name: ğŸ˜‡ é—®é¢˜åé¦ˆ
    url: https://gitee.com/layui/layui/issues
    about: ä½¿ç”¨ Layui è¿‡ç¨‹ä¸­é‡åˆ°çš„ Bugã€å¼‚å¸¸æˆ–å…¶ä»–åŠŸèƒ½å›°æƒ‘ã€‚
  - name: ğŸ“„ å®˜æ–¹æ–‡æ¡£
    url: https://layui.dev/
    about: å»ºè®®æ‚¨åœ¨åˆ›å»º Issue ä¹‹å‰ï¼Œä»”ç»†æŸ¥é˜… Layui å¼€å‘æ–‡æ¡£ï¼Œä»¥ä¾¿å¯¹å…¶æœ‰æ›´æ·±å…¥çš„äº†è§£ï¼Œå’Œæ›´å¥½åœ°åˆ†æé—®é¢˜ã€‚
