blank_issues_enabled: false
contact_links:
  - name: ğŸ˜„ åˆ›å»ºè®®é¢˜
    url: https://github.com/layui/layui/issues/new?template=bug-feature.yml
    about: ä¸ºäº†åŠ å¼º Issue è§„èŒƒã€æå‡æ²Ÿé€šæ•ˆç‡ï¼ŒLayui Issues å·²ç»Ÿä¸€åœ¨ Github å—ç†
  - name: ğŸ“„ å®˜æ–¹æ–‡æ¡£
    url: https://layui.dev/
    about: å»ºè®®åœ¨åˆ›å»º Issue ä¹‹å‰ï¼Œä»”ç»†æŸ¥é˜… Layui å¼€å‘æ–‡æ¡£ï¼Œä»¥ä¾¿å¯¹å…¶æœ‰æ›´æ·±å…¥çš„äº†è§£ï¼Œå’Œæ›´å¥½åœ°åˆ†æé—®é¢˜ã€‚
