name: Issue Labeled

on:
  issues:
    types: [labeled]

permissions:
  contents: read

jobs:
  issue-labeled:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: help wanted
        if: github.event.label.name == 'help wanted'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            @${{ github.event.issue.user.login }}  å¾ˆæ£’ ğŸ‘‹
            æˆ‘ä»¬æœ‰æ„æ„¿é‡‡çº³è¿™é¡¹è®®é¢˜ï¼Œæ¬¢è¿æ‚¨åˆ›å»º [Pull Request](https://github.com/layui/layui/pulls) æ¥ååŠ©å®ç°ï¼Œè‹¥å˜æ›´å†…å®¹æ¶‰åŠåˆ° API æ–°å¢å’Œæ”¹åŠ¨ï¼Œé™¤äº†æäº¤æ ¸å¿ƒä»£ç å¤–ï¼Œè¿˜éœ€åŒ…å«ï¼š[æ–‡æ¡£](https://github.com/layui/layui/tree/main/docs)ã€æµ‹è¯•ç”¨ä¾‹ç­‰ç›¸å…³æ–‡ä»¶ï¼Œä»¥ä¾¿æˆ‘ä»¬æ›´å¥½åœ°è¿›è¡Œ Reviewã€‚æœŸå¾…æ‚¨çš„è´¡çŒ®!

      - name: invalid
        if: github.event.label.name == 'invalid'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            @${{ github.event.issue.user.login }} ä½ å¥½ï¼Œä¸ºäº†æå‡æ²Ÿé€šæ•ˆç‡ï¼Œæˆ‘ä»¬å¯¹ Issue åˆ¶å®šäº†è§„èŒƒè¦æ±‚ï¼Œä½ çš„ Issue å› ä¸ç¬¦åˆè§„èŒƒè€Œè¢«è‡ªåŠ¨å…³é—­ã€‚
            å»ºè®®æ‚¨åœ¨ä¸‹æ¬¡åˆ›å»º Issue æ—¶ï¼Œéµå¾ªè¡¨å•æ¨¡æ¿è§„èŒƒå¡«å†™ã€‚è°¢è°¢ã€‚
            > ç›¸å…³å»¶ä¼¸ï¼šğŸ‘‰ [**æé—®çš„æ™ºæ…§**](https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way)
      
      - name: need reproduce
        if: github.event.label.name == 'need reproduce'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            @${{ github.event.issue.user.login }} æ‚¨å¥½ï¼Œè¯·æä¾›ä¸€ä¸ªæœ€å°åŒ–çš„é‡ç°ï¼Œä»¥ä¾¿æˆ‘ä»¬ä¸ºæ‚¨ååŠ©æ’æŸ¥é—®é¢˜ã€‚è‰¯å¥½çš„é‡ç°åº”å½“åŒ…æ‹¬ä½†ä¸ä»…é™äºï¼š
            - äº§ç”Ÿé—®é¢˜çš„è¯¦ç»†æ­¥éª¤
            - ä¸é—®é¢˜ç›¸å…³çš„å®Œæ•´ä»£ç 
            - åœ¨çº¿ Demo (æ¨èé€šè¿‡ [stackblitz](https://stackblitz.com/) æˆ– [codepen](https://codepen.io/) åˆ›å»º)
            > ç›¸å…³å»¶ä¼¸ï¼šğŸ‘‰ [ä¸ºä»€ä¹ˆè¦æä¾›æœ€å°åŒ–é‡ç°ï¼Ÿ](https://antfu.me/posts/why-reproductions-are-required-zh)

      - name: discussion
        if: github.event.label.name == 'discussion'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            @${{ github.event.issue.user.login }} ä½ å¥½ï¼ŒIssue ä¸€èˆ¬åªæ¥å—ã€ŒBug æŠ¥å‘Šã€å’Œã€Œæ–°åŠŸèƒ½è¯·æ±‚ã€ï¼Œè€Œæ‚¨çš„è®®é¢˜æ¶‰åŠåˆ°åŸºç¡€ç”¨æ³•å’ŒåŠŸèƒ½ç–‘æƒ‘ç­‰ä¸šåŠ¡ç›¸å…³çš„è®¨è®ºï¼Œè¿™å¹¶ä¸é€‚åˆä½œä¸º Issue è®¨è®ºã€‚å»ºè®®æ‚¨é€šè¿‡ä»¥ä¸‹æ–¹å¼å¯»æ±‚è§£å†³æ–¹æ¡ˆï¼š
            - ä»”ç»†æŸ¥é˜… Layui å®˜æ–¹æ–‡æ¡£ï¼šhttps://layui.dev
            - æœç´¢ç›¸å…³æŠ€æœ¯èµ„æ–™æˆ–å’¨è¯¢äººå·¥æ™ºèƒ½å¤§æ¨¡å‹
            - [Discussions](https://github.com/layui/layui/discussions)
            
      - name: unrelated
        if: github.event.label.name == 'unrelated'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            @${{ github.event.issue.user.login }} ç»è¿‡ç¡®è®¤ï¼Œæ‚¨æå‡ºçš„é—®é¢˜ä¸ Layui ä¸å­˜åœ¨ç›¸å…³è”ã€‚å»ºè®®é€šè¿‡ä»¥ä¸‹æ–¹å¼å¯»æ±‚è§£å†³æ–¹æ¡ˆï¼š
            - æœç´¢ç›¸å…³æŠ€æœ¯èµ„æ–™æˆ–å’¨è¯¢äººå·¥æ™ºèƒ½å¤§æ¨¡å‹
            - [Discussions](https://github.com/layui/layui/discussions)
