name: Issue Labeled

on:
  issues:
    types: [labeled]

permissions:
  contents: read

jobs:
  issue-labeled:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: content template
        id: template
        run: |
          contribute="è¯¦è§ï¼šðŸ€ [Layui Issue è´¡çŒ®æŒ‡å—](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)"
          echo "CONTRIBUTING=$contribute" >> $GITHUB_OUTPUT

      - name: help wanted
        if: github.event.label.name == 'help wanted'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            @${{ github.event.issue.user.login }} ä½ å¥½ ðŸ‘‹ã€‚
            æˆ‘ä»¬èµžæˆä¸ºè¯¥è®®é¢˜å¯»æ±‚ç¤¾åŒºå¸®åŠ©ï¼Œæ¬¢è¿Žåˆ›å»º [Pull Request](https://github.com/layui/layui/pulls) æ¥ååŠ©å®žçŽ°ï¼Œè‹¥å˜æ›´å†…å®¹æ¶‰åŠåˆ° API æ–°å¢žå’Œæ”¹åŠ¨ï¼Œé™¤äº†æäº¤æ ¸å¿ƒä»£ç å¤–ï¼Œè¿˜éœ€åŒ…å«ï¼šæ–‡æ¡£ã€æµ‹è¯•ç”¨ä¾‹ç­‰ç›¸å…³æ–‡ä»¶ï¼Œä»¥ä¾¿æˆ‘ä»¬æ›´å¥½åœ°è¿›è¡Œ Reviewã€‚æœŸå¾…æ‚¨çš„è´¡çŒ®!
            > ${{ steps.template.outputs.CONTRIBUTING }}

      - name: invalid
        if: github.event.label.name == 'invalid'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            @${{ github.event.issue.user.login }} ä½ å¥½ï¼Œä¸ºäº†æå‡æ²Ÿé€šæ•ˆçŽ‡ï¼Œæˆ‘ä»¬å¯¹ Issue åˆ¶å®šäº†ä¸¥æ ¼çš„è¦æ±‚ï¼Œä½ çš„ Issue å› ä¸ç¬¦åˆè§„å®šè€Œè¢«è‡ªåŠ¨å…³é—­ã€‚
            å»ºè®®ä½ åœ¨ä¸‹æ¬¡åˆ›å»º Issue æ—¶ï¼Œéµå¾ªç›¸åº”è§„èŒƒå’Œç¤¾åŒºè¡Œä¸ºå‡†åˆ™ã€‚è°¢è°¢ã€‚
            > ${{ steps.template.outputs.CONTRIBUTING }}
      
      - name: need reproduce
        if: github.event.label.name == 'need reproduce'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            @${{ github.event.issue.user.login }} ä½ å¥½ï¼Œè¯·æä¾›ä¸€ä¸ªæœ€å°åŒ–çš„é‡çŽ°ï¼Œä»¥ä¾¿æˆ‘ä»¬ä¸ºä½ ååŠ©æŽ’æŸ¥é—®é¢˜ã€‚è‰¯å¥½çš„é‡çŽ°åº”å½“åŒ…æ‹¬ä½†ä¸ä»…é™äºŽï¼š
            - äº§ç”Ÿé—®é¢˜çš„è¯¦ç»†æ­¥éª¤
            - ä¸Žé—®é¢˜ç›¸å…³çš„å®Œæ•´ä»£ç 
            - åœ¨çº¿ Demo (æŽ¨èé€šè¿‡ [stackblitz](https://stackblitz.com/) æˆ– [codepen](https://codepen.io/) åˆ›å»º)
            > ${{ steps.template.outputs.CONTRIBUTING }}
            > å»¶ä¼¸ï¼šðŸ‘‰ [ä¸ºä»€ä¹ˆè¦æä¾›æœ€å°åŒ–é‡çŽ°ï¼Ÿ](https://antfu.me/posts/why-reproductions-are-required-zh)

      - name: discussion
        if: github.event.label.name == 'discussion'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            @${{ github.event.issue.user.login }} ä½ å¥½ï¼ŒIssue åªæŽ¥å—ã€ŒBug æŠ¥å‘Šã€å’Œã€ŒåŠŸèƒ½è¯·æ±‚ã€ï¼Œè€Œä½ çš„è®®é¢˜æ¶‰åŠåˆ°å¦‚ä½•ä½¿ç”¨ã€åŠŸèƒ½ç–‘æƒ‘æˆ–å…¶ä»–ä¸šåŠ¡ç›¸å…³çš„é—®é¢˜ï¼Œè¿™å¹¶ä¸é€‚åˆä½œä¸º Issue è®¨è®ºã€‚å»ºè®®ä½ é€šè¿‡ä»¥ä¸‹æ–¹å¼å¯»æ±‚è§£å†³æ–¹æ¡ˆï¼š
            - ä»”ç»†æŸ¥é˜… Layui å®˜æ–¹æ–‡æ¡£ï¼šhttps://layui.dev
            - é€šè¿‡å…¶ä»–æŠ€æœ¯ç¤¾åŒºæœç´¢ç›¸å…³èµ„æ–™ã€æˆ–å……åˆ†åˆ©ç”¨å½“å‰ä¸»æµçš„äººå·¥æ™ºèƒ½å¤§æ¨¡åž‹
            - [Discussions](https://github.com/layui/layui/discussions)
            > ${{ steps.template.outputs.CONTRIBUTING }}
            
      - name: unrelated
        if: github.event.label.name == 'unrelated'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            @${{ github.event.issue.user.login }} ä½ æå‡ºçš„é—®é¢˜ä¸Ž Layui å¯èƒ½ä¸å­˜åœ¨ç›¸å…³è”ã€‚å»ºè®®é€šè¿‡ä»¥ä¸‹æ–¹å¼å¯»æ±‚è§£å†³æ–¹æ¡ˆï¼š
            - é€šè¿‡å…¶ä»–æŠ€æœ¯ç¤¾åŒºæœç´¢ç›¸å…³èµ„æ–™ã€æˆ–å……åˆ†åˆ©ç”¨å½“å‰ä¸»æµçš„äººå·¥æ™ºèƒ½å¤§æ¨¡åž‹
            - [Discussions](https://github.com/layui/layui/discussions)
            > ${{ steps.template.outputs.CONTRIBUTING }}
